# Generated by Django 5.2.8 on 2025-11-20 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('position', models.CharField(max_length=150, verbose_name='Cargo/Empresa')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto')),
                ('content', models.TextField(verbose_name='Depoimento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.IntegerField(default=0, help_text='Ordem de exibição (menor aparece primeiro)', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
