# Generated by Django 5.2.8 on 2025-11-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_processoabertura_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do plano (ex: Bronze, Prata, Ouro)', max_length=100)),
                ('categoria', models.CharField(choices=[('servicos', 'Serviços'), ('comercio', 'Comércio'), ('abertura', 'Abertura de Empresa')], default='servicos', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço mensal do plano', max_digits=10)),
                ('preco_antigo', models.DecimalField(blank=True, decimal_places=2, help_text='Preço anterior (para mostrar desconto)', max_digits=10, null=True)),
                ('descricao', models.TextField(help_text='Breve descrição do plano')),
                ('features', models.JSONField(default=list, help_text="Lista de características/benefícios do plano. Ex: ['Contabilidade completa', 'Certificado digital']")),
                ('mercadopago_price_id', models.CharField(blank=True, help_text='ID do preço/produto no Mercado Pago para integração de pagamento', max_length=200, null=True)),
                ('ativo', models.BooleanField(default=True, help_text='Se o plano está ativo e disponível para contratação')),
                ('destaque', models.BooleanField(default=False, help_text="Marcar como 'Mais Popular' ou em destaque")),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor número aparece primeiro)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['categoria', 'ordem', 'preco'],
            },
        ),
    ]
