# Generated by Django 5.2.8 on 2025-11-22 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Consultoria, Software, Educação', max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('ordem', models.IntegerField(default=0, help_text='Menor número aparece primeiro', verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria CNAE',
                'verbose_name_plural': 'Categorias CNAE',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: 6201-5/01, 8599-6/99', max_length=20, unique=True, verbose_name='Código CNAE')),
                ('descricao', models.TextField(help_text='Descrição completa da atividade econômica', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Se o CNAE está ativo para consulta', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnaes', to='services.categoriacnae', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'CNAE',
                'verbose_name_plural': 'CNAEs',
                'ordering': ['categoria__ordem', 'categoria__nome', 'codigo'],
            },
        ),
    ]
