# Generated by Django 5.2.9 on 2025-12-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_categoriacnae_cnae'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='features',
        ),
        migrations.AddField(
            model_name='plano',
            name='features_excluded',
            field=models.JSONField(blank=True, default=list, help_text='Lista de recursos NÃO incluídos no plano. Exemplo: ["Folha de Pagamentos", "Consultoria Tributária"]', verbose_name='Recursos NÃO Incluídos ❌'),
        ),
        migrations.AddField(
            model_name='plano',
            name='features_included',
            field=models.JSONField(blank=True, default=list, help_text='Lista de recursos INCLUÍDOS no plano. Exemplo: ["Contabilidade Completa", "Certificado Digital", "Suporte por WhatsApp"]', verbose_name='Recursos Incluídos ✅'),
        ),
    ]
