# Generated by Django 5.2.9 on 2025-12-20 01:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_add_features_included_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoabertura',
            name='iptu_imovel',
            field=models.FileField(blank=True, null=True, upload_to='processos_abertura/documentos/', verbose_name='Inscrição Imobiliária/IPTU'),
        ),
        migrations.AlterField(
            model_name='processoabertura',
            name='etapa_atual',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='processoabertura',
            name='plano_selecionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.plano'),
        ),
        migrations.AlterField(
            model_name='processoabertura',
            name='tipo_atividade',
            field=models.CharField(blank=True, choices=[('servico', 'Serviço'), ('comercio', 'Comércio')], max_length=20, null=True),
        ),
    ]
