# Generated by Django 5.2.10 on 2026-01-30 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_pagamento_delete_payment_and_more'),
        ('services', '0006_processoabertura_iptu_imovel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAberturaMEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente Pagamento'), ('pago', 'Pago - Aguardando Processamento'), ('em_andamento', 'Em Andamento'), ('documentacao', 'Aguardando Documentação'), ('analise', 'Em Análise'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome_completo', models.CharField(help_text='Nome completo como consta no documento de identidade', max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(help_text='E-mail para contato e acompanhamento', max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(help_text='Telefone com DDD para contato', max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(help_text='CPF no formato 000.000.000-00', max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, help_text='Número do RG', max_length=20, null=True, verbose_name='RG')),
                ('orgao_expedidor_rg', models.CharField(blank=True, help_text='Ex: SSP, DETRAN, IFP', max_length=20, null=True, verbose_name='Órgão Expedidor')),
                ('uf_orgao_expedidor', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF do Órgão Expedidor')),
                ('cnae_primario', models.CharField(help_text='Atividade principal do MEI', max_length=100, verbose_name='CNAE Primário')),
                ('cnae_secundario', models.CharField(blank=True, help_text='Atividade complementar (opcional)', max_length=100, null=True, verbose_name='CNAE Secundário')),
                ('forma_atuacao', models.CharField(choices=[('estabelecimento_fixo', 'Estabelecimento fixo'), ('internet', 'Internet'), ('porta_a_porta', 'Porta a porta'), ('televenda', 'Televenda'), ('correios', 'Correios'), ('local_fixo_fora_loja', 'Em local fixo fora da loja'), ('maquinas_automaticas', 'Máquinas automáticas')], help_text='Como o MEI vai exercer suas atividades', max_length=30, verbose_name='Forma de Atuação')),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, help_text='Valor inicial investido no negócio (opcional)', max_digits=12, null=True, verbose_name='Capital Social')),
                ('cep', models.CharField(help_text='CEP no formato 00000-000', max_length=10, verbose_name='CEP')),
                ('logradouro', models.CharField(help_text='Rua, Avenida, etc.', max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, help_text='Apto, Bloco, Sala, etc. (opcional)', max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações internas sobre o processo', null=True, verbose_name='Observações')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_mei', to='payments.pagamento', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Solicitação de Abertura MEI',
                'verbose_name_plural': 'Solicitações de Abertura MEI',
                'ordering': ['-criado_em'],
            },
        ),
    ]
