# Generated by Django 5.2.10 on 2026-01-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_solicitacaoaberturamei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoaberturamei',
            name='cnae_primario',
            field=models.CharField(help_text='Atividade principal do MEI', max_length=255, verbose_name='CNAE Primário'),
        ),
        migrations.AlterField(
            model_name='solicitacaoaberturamei',
            name='cnae_secundario',
            field=models.CharField(blank=True, help_text='Atividade complementar (opcional)', max_length=255, null=True, verbose_name='CNAE Secundário'),
        ),
    ]
