# Generated by Django 5.2.11 on 2026-02-05 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_solicitacaoaberturamei_cnae_primario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome do serviço (ex: Rescisão Retroativa)', max_length=200, verbose_name='Título do Serviço')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do serviço em R$', max_digits=10, verbose_name='Valor')),
                ('descricao', models.TextField(help_text='Descrição detalhada do serviço', verbose_name='Descrição')),
                ('icone', models.CharField(default='fas fa-file-alt', help_text='Classe do ícone FontAwesome (ex: fas fa-file-alt)', max_length=50, verbose_name='Ícone')),
                ('ativo', models.BooleanField(default=True, help_text='Se o serviço está disponível para contratação', verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor número aparece primeiro)', verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço Avulso',
                'verbose_name_plural': 'Serviços Avulsos',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.AlterField(
            model_name='plano',
            name='categoria',
            field=models.CharField(choices=[('servicos', 'Serviços'), ('comercio', 'Comércio'), ('abertura', 'Abertura de Empresa'), ('mei', 'MEI - Contabilidade')], default='servicos', max_length=20),
        ),
        migrations.CreateModel(
            name='ContratacaoServicoAvulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando_pagamento', 'Aguardando Pagamento'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=30, verbose_name='Status')),
                ('valor_contratado', models.DecimalField(decimal_places=2, help_text='Valor do serviço no momento da contratação', max_digits=10, verbose_name='Valor Contratado')),
                ('observacoes_cliente', models.TextField(blank=True, help_text='Observações enviadas pelo cliente ao contratar', null=True, verbose_name='Observações do Cliente')),
                ('observacoes_internas', models.TextField(blank=True, help_text='Anotações internas sobre o andamento do serviço', null=True, verbose_name='Observações Internas')),
                ('visualizado', models.BooleanField(default=False, help_text='Se a equipe já visualizou essa contratação', verbose_name='Visualizado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratacoes_servicos_avulsos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratacoes', to='services.servicoavulso', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Contratação de Serviço Avulso',
                'verbose_name_plural': 'Contratações de Serviços Avulsos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
