# Generated by Django 5.2.11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servicoavulso_alter_plano_categoria_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoBaixaMEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ do MEI')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('motivo', models.CharField(blank=True, choices=[('encerramento', 'Encerramento das atividades'), ('transicao_me', 'Transição para ME'), ('falecimento', 'Falecimento do titular'), ('outros', 'Outros motivos')], max_length=30, null=True, verbose_name='Motivo da Baixa')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente Pagamento'), ('pago', 'Pago - Aguardando Processamento'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_baixa_mei', to='payments.pagamento', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Solicitação de Baixa MEI',
                'verbose_name_plural': 'Solicitações de Baixa MEI',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoDeclaracaoAnualMEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ do MEI')),
                ('ano_referencia', models.CharField(max_length=4, verbose_name='Ano de Referência')),
                ('faturamento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Faturamento Anual')),
                ('teve_funcionario', models.BooleanField(default=False, verbose_name='Teve funcionário no período?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente Pagamento'), ('pago', 'Pago - Aguardando Processamento'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_dasn_mei', to='payments.pagamento', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Solicitação de Declaração Anual MEI',
                'verbose_name_plural': 'Solicitações de Declaração Anual MEI',
                'ordering': ['-criado_em'],
            },
        ),
    ]
