# Generated by Django 5.2.9 on 2026-01-02 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entrada', 'A Receber'), ('saida', 'A Pagar')], max_length=10, verbose_name='Tipo')),
                ('description', models.CharField(max_length=255, verbose_name='Fornecedor/Cliente')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Recorrente (Mensal)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Liquidado')], default='pendente', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_transactions', to='finance.account', verbose_name='Conta/Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_scheduled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta Agendada',
                'verbose_name_plural': 'Contas Agendadas',
                'ordering': ['due_date'],
            },
        ),
    ]
