# Generated by Django 5.2.10 on 2026-01-09 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_scheduledtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição (OFX)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('fitid', models.CharField(max_length=255, verbose_name='ID Transação Banco')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('importado', 'Aprovado'), ('ignorado', 'Ignorado')], default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account', verbose_name='Categoria Sugerida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conciliação',
                'verbose_name_plural': 'Conciliações',
                'unique_together': {('fitid', 'user')},
            },
        ),
    ]
