# Generated by Django 5.2.10 on 2026-01-09 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_bankreconciliation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, help_text='Ex: 1.1.01', max_length=20, null=True, verbose_name='Código Contábil'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_synthetic',
            field=models.BooleanField(default=False, verbose_name='Conta Sintética (Agrupadora)'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.account', verbose_name='Conta Pai'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.subcategory', verbose_name='Subcategoria'),
        ),
    ]
