# Generated by Django 5.2.8 on 2025-11-13 22:54

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to=apps.documents.models.document_upload_path, verbose_name='Arquivo')),
                ('categoria', models.CharField(choices=[('relatorio', 'Relatório'), ('contrato', 'Contrato'), ('comprovante', 'Comprovante'), ('declaracao', 'Declaração'), ('nota_fiscal', 'Nota Fiscal'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria')),
                ('visivel_para_cliente', models.BooleanField(default=True, verbose_name='Visível para Cliente')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
