# Generated by Django 5.2.8 on 2025-11-21 18:19

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_pdf', models.FileField(help_text='Envie o arquivo da nota fiscal em formato PDF', upload_to=apps.documents.models.nota_fiscal_upload_path, verbose_name='Arquivo PDF')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('observacoes', models.TextField(blank=True, help_text='Observações internas sobre esta nota fiscal', null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(help_text='Cliente que receberá a nota fiscal', on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('enviado_por', models.ForeignKey(help_text='Membro da equipe que fez o upload', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-data_upload'],
            },
        ),
    ]
