# Generated by Django 5.2.8 on 2025-11-21 18:50

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_notafiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome descritivo do documento (ex: Contrato Social da Empresa, Alvará de Funcionamento)', max_length=200, verbose_name='Título do Documento')),
                ('categoria', models.CharField(choices=[('contrato_social', 'Contrato Social'), ('alvara', 'Alvará'), ('certidao', 'Certidão'), ('procuracao', 'Procuração'), ('registro', 'Registro'), ('declaracao', 'Declaração'), ('relatorio', 'Relatório'), ('outros', 'Outros')], default='outros', help_text='Tipo do documento', max_length=20, verbose_name='Categoria')),
                ('arquivo', models.FileField(help_text='Envie o arquivo do documento (PDF, DOC, DOCX, etc.)', upload_to=apps.documents.models.documento_empresa_upload_path, verbose_name='Arquivo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional sobre o documento (opcional)', null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('cliente', models.ForeignKey(help_text='Cliente que receberá o documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('enviado_por', models.ForeignKey(help_text='Membro da equipe que fez o upload', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_empresa_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento da Empresa',
                'verbose_name_plural': 'Documentos da Empresa',
                'ordering': ['-data_upload'],
            },
        ),
    ]
