# Generated by Django 5.2.8 on 2025-11-21 19:12

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentoempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(help_text='Mês e ano do extrato (ex: 01/2025, 11/2024)', max_length=7, verbose_name='Mês/Ano')),
                ('arquivo', models.FileField(help_text='Envie o arquivo do extrato bancário (PDF, imagem, etc.)', upload_to=apps.documents.models.extrato_bancario_upload_path, verbose_name='Arquivo do Extrato')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre este extrato (opcional)', null=True, verbose_name='Observações')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
                ('cliente', models.ForeignKey(help_text='Cliente que enviou o extrato', on_delete=django.db.models.deletion.CASCADE, related_name='extratos_bancarios', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Extrato Bancário',
                'verbose_name_plural': 'Extratos Bancários',
                'ordering': ['-data_upload'],
                'unique_together': {('cliente', 'mes_ano', 'arquivo')},
            },
        ),
    ]
