# Generated by Django 5.2.8 on 2025-11-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_extratobancario'),
    ]

    operations = [
        migrations.AddField(
            model_name='extratobancario',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data final do período'),
        ),
        migrations.AddField(
            model_name='extratobancario',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data inicial do período'),
        ),
    ]
