# Generated by Django 5.2.8 on 2025-12-03 00:00

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_extratobancario_end_date_extratobancario_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Arquivo do documento (PDF, DOC, DOCX, XLS, etc.)', max_length=500, upload_to=apps.documents.models.documento_cliente_upload_path, verbose_name='Arquivo')),
                ('tipo_documento', models.CharField(choices=[('contrato_social', 'Contrato Social'), ('alteracao_contratual', 'Alteração Contratual'), ('certidao_negativa', 'Certidão Negativa'), ('guia_impostos', 'Guia de Impostos'), ('balanco_patrimonial', 'Balanço Patrimonial'), ('dre', 'DRE - Demonstração do Resultado'), ('folha_pagamento', 'Folha de Pagamento'), ('declaracao_ir', 'Declaração de IR'), ('alvara', 'Alvará'), ('licenca', 'Licença'), ('procuracao', 'Procuração'), ('relatorio_contabil', 'Relatório Contábil'), ('documento_fiscal', 'Documento Fiscal'), ('outros', 'Outros')], db_index=True, help_text='Categoria/tipo do documento', max_length=30, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(help_text='Título descritivo do documento', max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional ou observações sobre o documento (opcional)', null=True, verbose_name='Descrição')),
                ('data_envio', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Envio')),
                ('visualizado', models.BooleanField(default=False, help_text='Indica se o cliente já visualizou este documento', verbose_name='Visualizado')),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Visualização')),
                ('notificacao_enviada', models.BooleanField(default=False, help_text='Indica se o e-mail de notificação foi enviado com sucesso', verbose_name='Notificação Enviada')),
                ('data_notificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Notificação')),
                ('cliente', models.ForeignKey(help_text='Cliente que receberá este documento', limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('enviado_por', models.ForeignKey(help_text='Membro da equipe que fez o upload', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados_clientes', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento do Cliente',
                'verbose_name_plural': 'Documentos dos Clientes',
                'ordering': ['-data_envio'],
                'indexes': [models.Index(fields=['cliente', '-data_envio'], name='documents_d_cliente_d5f8c1_idx'), models.Index(fields=['tipo_documento', '-data_envio'], name='documents_d_tipo_do_4d83a6_idx'), models.Index(fields=['notificacao_enviada'], name='documents_d_notific_afff47_idx')],
            },
        ),
    ]
