# Generated by Django 5.2.10 on 2026-01-13 19:37

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documentocliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.documents.models.nota_fiscal_cliente_upload_path, verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('em_analise', 'Em Análise'), ('processado', 'Processado'), ('rejeitado', 'Rejeitado')], default='enviado', max_length=20, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais_enviadas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Nota Fiscal (Cliente)',
                'verbose_name_plural': 'Notas Fiscais (Clientes)',
                'ordering': ['-data_envio'],
            },
        ),
    ]
