# Generated by Django 5.2.10 on 2026-01-13 21:24

import apps.documents.models_guia_imposto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_notafiscalcliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('das', 'DAS'), ('inss', 'INSS'), ('fgts', 'FGTS'), ('irrf', 'IRRF'), ('iss', 'ISS'), ('icms', 'ICMS'), ('pis', 'PIS'), ('cofins', 'COFINS'), ('csll', 'CSLL'), ('irpj', 'IRPJ'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Imposto')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('competencia', models.DateField(help_text='Primeiro dia do mês de referência', verbose_name='Competência (Mês Referência)')),
                ('status', models.CharField(choices=[('a_vencer', 'A Vencer'), ('pago', 'Pago'), ('atrasado', 'Em Atraso')], default='a_vencer', max_length=20, verbose_name='Status de Pagamento')),
                ('arquivo_pdf', models.FileField(upload_to=apps.documents.models_guia_imposto.guia_imposto_upload_path, verbose_name='Arquivo PDF (Guia)')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to=apps.documents.models_guia_imposto.guia_imposto_upload_path, verbose_name='Comprovante de Pagamento')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_imposto', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Guia de Imposto',
                'verbose_name_plural': 'Guias de Impostos',
                'ordering': ['status', 'vencimento'],
            },
        ),
    ]
