# Generated by Django 5.2.11 on 2026-02-06 19:02

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_guiaimposto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletoContabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(help_text='Mês/ano de referência do boleto (ex: Janeiro/2026)', max_length=50, verbose_name='Mês de Referência')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do boleto em reais', max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(help_text='Data de vencimento do boleto', verbose_name='Data de Vencimento')),
                ('arquivo_boleto', models.FileField(help_text='Arquivo PDF do boleto', upload_to=apps.documents.models.boleto_contabilidade_upload_path, verbose_name='Arquivo do Boleto')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, help_text='Observações internas sobre este boleto', null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(help_text='Cliente que receberá o boleto', on_delete=django.db.models.deletion.CASCADE, related_name='boletos_contabilidade', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('enviado_por', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Boleto Contabilidade',
                'verbose_name_plural': 'Boletos Contabilidade',
                'ordering': ['-criado_em'],
            },
        ),
    ]
