# Generated by Django 5.2.8 on 2025-12-08 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('services', '0004_categoriacnae_cnae'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_reference', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Referência externa única para o Mercado Pago', unique=True)),
                ('cliente_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do Cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Cliente')),
                ('cliente_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF do Cliente')),
                ('cliente_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Cliente')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('mp_payment_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID do Pagamento MP')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Preferência MP')),
                ('mp_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status MP')),
                ('mp_status_detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Detalhe do Status MP')),
                ('mp_payment_method_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento')),
                ('mp_payment_type_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Pagamento')),
                ('mp_response_data', models.JSONField(blank=True, help_text='Dados completos retornados pelo Mercado Pago', null=True, verbose_name='Dados da Resposta MP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='services.plano')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['status', 'criado_em'], name='payments_pa_status_99b62e_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['external_reference'], name='payments_pa_externa_77dc31_idx'),
        ),
    ]
