# Generated by Django 5.2.8 on 2025-11-27 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mês para representar competência (YYYY-MM-01)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='movimentacoes/%Y/%m')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('transmitido', 'Transmitido'), ('processado', 'Processado'), ('com_pendencia', 'Com Pendência')], default='rascunho', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação Financeira',
                'verbose_name_plural': 'Movimentações Financeiras',
                'ordering': ['-competencia', '-created_at'],
            },
        ),
    ]
