# Generated by Django 5.2.8 on 2025-11-27 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_movimentacaofinanceira'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissaoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mês para representar competência (YYYY-MM-01)')),
                ('transmitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transmissão Mensal',
                'verbose_name_plural': 'Transmissões Mensais',
                'ordering': ['-competencia'],
            },
        ),
        migrations.AddField(
            model_name='movimentacaofinanceira',
            name='transmissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='users.transmissaomensal'),
        ),
    ]
