# Generated by Django 5.2.8 on 2025-11-27 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_transmissaomensal_movimentacaofinanceira_transmissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertidaoNegativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('federal', 'Federal'), ('estadual', 'Estadual'), ('trabalhista', 'Trabalhista'), ('fgts', 'FGTS')], max_length=20)),
                ('status', models.CharField(choices=[('negativa', 'Negativa'), ('positiva', 'Positiva'), ('indisponivel', 'Indisponível')], default='negativa', max_length=20)),
                ('arquivo_pdf', models.FileField(upload_to='certidoes/%Y/%m')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certidoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certidão Negativa',
                'verbose_name_plural': 'Certidões Negativas',
                'ordering': ['-data_envio'],
            },
        ),
    ]
