# Generated by Django 5.2.9 on 2025-12-20 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_certidaonegativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='competencia',
            field=models.DateField(db_index=True, help_text='Use o primeiro dia do mês para representar competência (YYYY-MM-01)'),
        ),
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('transmitido', 'Transmitido'), ('processado', 'Processado'), ('com_pendencia', 'Com Pendência')], db_index=True, default='rascunho', max_length=20),
        ),
    ]
