# Generated by Django 5.2.8 on 2025-11-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Pergunta')),
                ('descricao', models.TextField(verbose_name='Resposta')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição no site (menor número aparece primeiro)', verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para ocultar esta dúvida do site', verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Dúvida Frequente',
                'verbose_name_plural': 'Dúvidas Frequentes',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
