# Generated by Django 5.2.8 on 2025-11-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_duvida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('servico_interesse', models.CharField(max_length=100, verbose_name='Serviço de Interesse')),
                ('origem', models.CharField(choices=[('popup', 'Popup da Home'), ('contato', 'Seção de Contato')], max_length=20, verbose_name='Origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('contatado', models.BooleanField(default=False, verbose_name='Foi Contatado?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-criado_em'],
            },
        ),
    ]
