# Generated by Django 5.2.8 on 2025-11-26 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_lead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contador_responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes_atendidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Chamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo_solicitacao",
                    models.CharField(
                        choices=[
                            ("nota_fiscal", "Emissão de Notas Fiscais"),
                            ("documentos", "Documentos da Empresa"),
                            ("boleto", "Boleto Bancário"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_andamento", "Em Andamento"),
                            ("resolvido", "Resolvido"),
                            ("fechado", "Fechado"),
                        ],
                        default="aberto",
                        max_length=20,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chamados",
                        to="support.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chamado",
                "verbose_name_plural": "Chamados",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
