# Generated by Django 5.2.8 on 2025-12-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_chamadoattachment_chamadomessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20),
        ),
    ]
