# Generated by Django 5.2.9 on 2025-12-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_chamado_data_atualizacao_chamado_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fase_abertura',
            field=models.CharField(choices=[('fase_1', 'Fase 1 — Planejamento e Análise Inicial'), ('fase_2', 'Fase 2 — Consulta de Viabilidade'), ('fase_3', 'Fase 3 — Registro Jurídico'), ('fase_4', 'Fase 4 — Inscrições Fiscais'), ('fase_5', 'Fase 5 — Licenças e Autorizações'), ('fase_6', 'Fase 6 — Enquadramento Tributário'), ('fase_7', 'Fase 7 — Empresa Aberta')], default='fase_1', max_length=20, verbose_name='Fase de Abertura'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contatado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Foi Contatado?'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Cadastro'),
        ),
    ]
