# Generated by Django 5.2.10 on 2026-01-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_stafftask'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='stafftask',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', max_length=20, verbose_name='Prioridade'),
        ),
    ]
