# Generated by Django 5.2.10 on 2026-01-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_stafftask_due_date_stafftask_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='regime_tributario',
            field=models.CharField(choices=[('MEI', 'MEI'), ('SN', 'Simples Nacional'), ('LP', 'Lucro Presumido'), ('LR', 'Lucro Real')], default='SN', max_length=5, verbose_name='Regime Tributário'),
        ),
    ]
