# Generated by Django 5.2.10 on 2026-01-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_cliente_regime_tributario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
