# Generated by Django 5.2.10 on 2026-01-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='servico_interesse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serviço de Interesse'),
        ),
    ]
