# Generated by Django 5.2.10 on 2026-01-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0013_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Event ID'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='google_html_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Evento'),
        ),
    ]
