# Generated by Django 5.2.10 on 2026-02-04 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0014_agenda_google_event_id_agenda_google_html_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=300, verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('categoria', models.CharField(blank=True, help_text='Categoria para agrupar perguntas (ex: Abertura de Empresa, Impostos, etc.)', max_length=100, null=True, verbose_name='Categoria')),
                ('palavras_chave', models.CharField(blank=True, help_text='Palavras separadas por vírgula para ajudar na busca (ex: cnpj, abrir, empresa)', max_length=500, null=True, verbose_name='Palavras-chave')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pergunta do Chatbot',
                'verbose_name_plural': 'Perguntas do Chatbot',
                'ordering': ['categoria', 'ordem', '-criado_em'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='origem',
            field=models.CharField(choices=[('popup', 'Popup da Home'), ('contato', 'Seção de Contato'), ('chatbot', 'Chatbot')], max_length=20, verbose_name='Origem'),
        ),
        migrations.CreateModel(
            name='ChatbotSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada')], default='ativa', max_length=20)),
                ('avaliacao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Avaliação (1-5)')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('pagina_origem', models.URLField(blank=True, null=True, verbose_name='Página de Origem')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_sessoes', to='support.lead')),
            ],
            options={
                'verbose_name': 'Sessão do Chatbot',
                'verbose_name_plural': 'Sessões do Chatbot',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bot', models.BooleanField(default=False, verbose_name='É do Bot?')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pergunta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.chatbotpergunta')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='support.chatbotsessao')),
            ],
            options={
                'verbose_name': 'Mensagem do Chatbot',
                'verbose_name_plural': 'Mensagens do Chatbot',
                'ordering': ['criado_em'],
            },
        ),
    ]
