# Generated by Django 5.2.11 on 2026-02-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_chatbotpergunta_alter_lead_origem_chatbotsessao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='certificado_digital_status',
            field=models.CharField(choices=[('nao_contratado', 'Não Contratado'), ('ativo', 'Ativo'), ('vencido', 'Vencido'), ('a_vencer', 'Próximo ao Vencimento')], default='nao_contratado', max_length=20, verbose_name='Status Certificado Digital'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='certificado_digital_tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Certificado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='certificado_digital_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade Certificado Digital'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço Completo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco_virtual_endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço Virtual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco_virtual_status',
            field=models.CharField(choices=[('nao_contratado', 'Não Contratado'), ('ativo', 'Ativo'), ('vencido', 'Vencido')], default='nao_contratado', max_length=20, verbose_name='Status Endereço Virtual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco_virtual_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Validade Endereço Virtual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
