# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0016_cliente_certificado_digital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='origem',
            field=models.CharField(
                choices=[
                    ('popup', 'Popup da Home'),
                    ('contato', 'Seção de Contato'),
                    ('chatbot', 'Chatbot'),
                    ('formulario_baixar_mei', 'Formulário Baixar MEI'),
                    ('formulario_declaracao_anual_mei', 'Formulário Declaração Anual MEI'),
                ],
                max_length=50,
                verbose_name='Origem',
            ),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estado',
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name='Estado',
            ),
        ),
        migrations.AlterField(
            model_name='lead',
            name='servico_interesse',
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name='Serviço de Interesse',
            ),
        ),
    ]
