# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0017_alter_lead_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='estado',
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name='Estado',
            ),
        ),
        migrations.AlterField(
            model_name='lead',
            name='servico_interesse',
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name='Serviço de Interesse',
            ),
        ),
    ]
