"""
Django settings for vetorial_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Carrega as variáveis de ambiente do arquivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', "django-insecure-k6a%y-a)m#2g#ir)y$rob$c4u-$ctq*at#p9_#y^)ak_$*+h$-")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else ['localhost', '127.0.0.1', 'vetorialcontabilidade.com.br', 'www.vetorialcontabilidade.com.br']

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = [
    'https://vetorialcontabilidade.com.br',
    'https://www.vetorialcontabilidade.com.br',
    'http://vetorialcontabilidade.com.br',
    'http://www.vetorialcontabilidade.com.br',
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
    
    # Apps do projeto Gestão 360
    "apps.users",
    "apps.dashboard",
    "apps.services",
    "apps.payments",
    "apps.support",
    "apps.documents",
    "apps.blog",
    "apps.testimonials",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "vetorial_project.middleware.CacheControlMiddleware",
    "vetorial_project.middleware.SecurityHeadersMiddleware",
]

ROOT_URLCONF = "gestao360_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Certidões alert
                "apps.users.context_processors.certidoes_alert",
            ],
        },
    },
]

WSGI_APPLICATION = "gestao360_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv('DB_NAME', 'gestao360_db'),
        "USER": os.getenv('DB_USER', 'postgres'),
        "PASSWORD": os.getenv('DB_PASSWORD', 'postgres'),
        "HOST": os.getenv('DB_HOST', 'localhost'),
        "PORT": os.getenv('DB_PORT', '5432'),
        # Otimizações de conexão
        "CONN_MAX_AGE": 600,  # Reutilizar conexões por 10 minutos
        "OPTIONS": {
            "connect_timeout": 10,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "apps.users.validators.UppercaseValidator",
    },
    {
        "NAME": "apps.users.validators.LowercaseValidator",
    },
    {
        "NAME": "apps.users.validators.SpecialCharacterValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Whitenoise configuration for production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Configurações adicionais do WhiteNoise
WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh apenas em desenvolvimento
WHITENOISE_USE_FINDERS = DEBUG  # Use finders apenas em desenvolvimento
WHITENOISE_MAX_AGE = 31536000 if not DEBUG else 0  # Cache de 1 ano em produção

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Modelo de usuário customizado
AUTH_USER_MODEL = 'users.CustomUser'

# Configurações do Mercado Pago
MERCADO_PAGO_PUBLIC_KEY = os.getenv('MP_PUBLIC_KEY', '')
MERCADO_PAGO_ACCESS_TOKEN = os.getenv('MP_ACCESS_TOKEN', '')

# Configurações de segurança (produção)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # SECURE_SSL_REDIRECT desabilitado - Nginx cuida dos redirecionamentos
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Configurações para uploads de movimentações financeiras
MOVIMENTACAO_ALLOWED_EXTENSIONS = ['pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx']
# 10 MB por arquivo por padrão
MOVIMENTACAO_MAX_UPLOAD_SIZE = 10 * 1024 * 1024

# ============================================================================
# CONFIGURAÇÕES DE E-MAIL
# ============================================================================

# Backend de e-mail (usar SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Configurações do servidor SMTP (Hotmail/Outlook)
EMAIL_HOST = 'smtp-mail.outlook.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'contabilidadevetorial@hotmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')  # Usar variável de ambiente

# Remetente padrão
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# URL base do site (para links nos e-mails)
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')

# ============================================================================
# CONFIGURAÇÕES DO CELERY (Tarefas Assíncronas)
# ============================================================================

# Broker URL (usar Redis em produção, ou RabbitMQ)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')

# Backend de resultados (opcional, para tasks que retornam valores)
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Aceitar conteúdo em JSON
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Timezone do Celery (deve ser o mesmo do Django)
CELERY_TIMEZONE = TIME_ZONE

# Configurações de retry
CELERY_TASK_ACKS_LATE = True  # Task só é marcada como concluída após execução
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Re-enfileira task se worker cair

# Timeout de tasks (10 minutos)
CELERY_TASK_TIME_LIMIT = 600

# Prefetch: quantas tasks cada worker pega de uma vez
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# ============================================================================
# CONFIGURAÇÕES DE LOGGING
# ============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'email_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'emails.log',
            'maxBytes': 5242880,  # 5 MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.services.email_service': {
            'handlers': ['console', 'email_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.documents.tasks': {
            'handlers': ['console', 'email_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.documents.signals': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Criar diretório de logs se não existir
import os
logs_dir = BASE_DIR / 'logs'
if not os.path.exists(logs_dir):
    os.makedirs(logs_dir)

# ============================================================================
# CONFIGURAÇÕES DE CACHE
# ============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'vetorial',
        'TIMEOUT': 300,  # 5 minutos padrão
    }
}

# Cache de sessão
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# ============================================================================
# OTIMIZAÇÕES DE TEMPLATES
# ============================================================================

# Cache de templates em produção
if not DEBUG:
    TEMPLATES[0]['OPTIONS']['loaders'] = [
        ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]),
    ]

# ============================================================================
# CONFIGURAÇÕES DE LGPD E SEGURANÇA
# ============================================================================

# Nunca anexar documentos em e-mails (apenas notificação)
EMAIL_ATTACH_DOCUMENTS = False

# Tempo de retenção de logs de notificação (em dias)
NOTIFICATION_LOG_RETENTION_DAYS = 90

# Limite de tamanho para documentos (20 MB)
DOCUMENTO_MAX_UPLOAD_SIZE = 20 * 1024 * 1024
